<?php

return [
    "CREATE TABLE IF NOT EXISTS crop_cycles (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        farm_id INT NOT NULL,
        plot_id INT NOT NULL,
        crop_type VARCHAR(100) NOT NULL,
        variety VARCHAR(100),
        season VARCHAR(50),
        crop_batch_id VARCHAR(100) UNIQUE NOT NULL,
        start_date DATE,
        end_date DATE,
        status ENUM('planning', 'procurement', 'nursery', 'field',
                    'monitoring', 'harvest', 'sales', 'completed') DEFAULT 'planning',
        budget DECIMAL(15, 2),
        expected_yield DECIMAL(10, 2),
        actual_yield DECIMAL(10, 2),
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (farm_id) REFERENCES farms(id),
        FOREIGN KEY (plot_id) REFERENCES plots(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_status (status),
        INDEX idx_crop_batch_id (crop_batch_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS crop_operations (
        id INT PRIMARY KEY AUTO_INCREMENT,
        crop_cycle_id INT NOT NULL,
        activity_type ENUM('planting', 'irrigation', 'spraying', 'weeding',
                           'fertilizing', 'monitoring', 'harvesting', 'other') NOT NULL,
        activity_date DATE NOT NULL,
        description TEXT,
        cost DECIMAL(15, 2),
        worker_ids JSON,
        gps_latitude DECIMAL(10, 8),
        gps_longitude DECIMAL(11, 8),
        photo_urls JSON,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (crop_cycle_id) REFERENCES crop_cycles(id) ON DELETE CASCADE,
        INDEX idx_crop_cycle_id (crop_cycle_id),
        INDEX idx_activity_date (activity_date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS crop_procurements (
        id INT PRIMARY KEY AUTO_INCREMENT,
        crop_cycle_id INT NOT NULL,
        supplier_id INT,
        item_type ENUM('seeds', 'fertilizers', 'tools', 'pesticides', 'other') NOT NULL,
        item_name VARCHAR(255) NOT NULL,
        quantity DECIMAL(10, 2),
        unit VARCHAR(50),
        cost DECIMAL(15, 2),
        purchase_date DATE,
        batch_number VARCHAR(100),
        expiry_date DATE,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (crop_cycle_id) REFERENCES crop_cycles(id) ON DELETE CASCADE,
        INDEX idx_crop_cycle_id (crop_cycle_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS harvest_records (
        id INT PRIMARY KEY AUTO_INCREMENT,
        crop_cycle_id INT NOT NULL,
        harvest_date DATE NOT NULL,
        quantity DECIMAL(10, 2),
        quality_grade VARCHAR(50),
        storage_location VARCHAR(255),
        photos JSON,
        verified_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (crop_cycle_id) REFERENCES crop_cycles(id) ON DELETE CASCADE,
        INDEX idx_crop_cycle_id (crop_cycle_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS crop_sales (
        id INT PRIMARY KEY AUTO_INCREMENT,
        crop_cycle_id INT NOT NULL,
        sale_date DATE NOT NULL,
        buyer_name VARCHAR(255),
        quantity DECIMAL(10, 2) NOT NULL,
        unit VARCHAR(50),
        unit_price DECIMAL(10, 2),
        total_amount DECIMAL(15, 2),
        payment_status ENUM('pending', 'paid', 'partial') DEFAULT 'pending',
        notes TEXT,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (crop_cycle_id) REFERENCES crop_cycles(id) ON DELETE CASCADE,
        INDEX idx_crop_cycle_id (crop_cycle_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
];
