<?php

return [
    "CREATE TABLE IF NOT EXISTS workers (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        user_id INT,
        employee_id VARCHAR(100) UNIQUE,
        name VARCHAR(255) NOT NULL,
        phone VARCHAR(50),
        email VARCHAR(255),
        role VARCHAR(100),
        department VARCHAR(100),
        hire_date DATE,
        hourly_rate DECIMAL(10, 2),
        emergency_contact VARCHAR(255),
        status ENUM('active', 'inactive', 'terminated') DEFAULT 'active',
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES users(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS attendance (
        id INT PRIMARY KEY AUTO_INCREMENT,
        worker_id INT NOT NULL,
        date DATE NOT NULL,
        clock_in TIME,
        clock_out TIME,
        gps_latitude_in DECIMAL(10, 8),
        gps_longitude_in DECIMAL(11, 8),
        gps_latitude_out DECIMAL(10, 8),
        gps_longitude_out DECIMAL(11, 8),
        photo_url VARCHAR(255),
        status ENUM('present', 'absent', 'late', 'half_day') DEFAULT 'present',
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
        UNIQUE KEY unique_attendance (worker_id, date),
        INDEX idx_worker_id (worker_id),
        INDEX idx_date (date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS tasks (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        assigned_to INT NOT NULL,
        assigned_by INT NOT NULL,
        farm_id INT,
        block_id INT,
        task_type VARCHAR(100) NOT NULL,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        priority ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium',
        deadline DATE,
        completed_at TIMESTAMP NULL,
        verified_at TIMESTAMP NULL,
        verification_photos JSON,
        gps_latitude DECIMAL(10, 8),
        gps_longitude DECIMAL(11, 8),
        status ENUM('pending', 'in_progress', 'completed', 'verified', 'canceled') DEFAULT 'pending',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (assigned_to) REFERENCES workers(id),
        FOREIGN KEY (assigned_by) REFERENCES workers(id),
        FOREIGN KEY (farm_id) REFERENCES farms(id),
        FOREIGN KEY (block_id) REFERENCES blocks(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_assigned_to (assigned_to),
        INDEX idx_status (status),
        INDEX idx_deadline (deadline)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS payroll (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        worker_id INT NOT NULL,
        pay_period_start DATE NOT NULL,
        pay_period_end DATE NOT NULL,
        hours_worked DECIMAL(8,2) DEFAULT 0,
        gross_amount DECIMAL(12,2) DEFAULT 0,
        deductions DECIMAL(12,2) DEFAULT 0,
        net_amount DECIMAL(12,2) DEFAULT 0,
        status ENUM('draft', 'approved', 'paid') DEFAULT 'draft',
        paid_at TIMESTAMP NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
        INDEX idx_organization_id (organization_id),
        INDEX idx_worker_id (worker_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
];
