<?php

return [
    "CREATE TABLE IF NOT EXISTS suppliers (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        contact_person VARCHAR(255),
        phone VARCHAR(50),
        email VARCHAR(255),
        address TEXT,
        tax_id VARCHAR(100),
        rating INT DEFAULT 1,
        payment_terms VARCHAR(100),
        status ENUM('active', 'inactive') DEFAULT 'active',
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        INDEX idx_organization_id (organization_id),
        INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS inventory_items (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        category VARCHAR(100) NOT NULL,
        name VARCHAR(255) NOT NULL,
        sku VARCHAR(100),
        unit VARCHAR(50),
        quantity DECIMAL(10, 2) DEFAULT 0,
        reorder_level DECIMAL(10, 2),
        supplier_id INT,
        purchase_price DECIMAL(10, 2),
        expiry_date DATE,
        storage_location VARCHAR(255),
        batch_number VARCHAR(100),
        description TEXT,
        status ENUM('active', 'inactive', 'discontinued') DEFAULT 'active',
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_category (category),
        INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS inventory_transactions (
        id INT PRIMARY KEY AUTO_INCREMENT,
        item_id INT NOT NULL,
        type ENUM('stock_in', 'stock_out', 'transfer', 'adjustment') NOT NULL,
        quantity DECIMAL(10, 2) NOT NULL,
        unit_cost DECIMAL(10, 2),
        total_cost DECIMAL(10, 2),
        reference_type VARCHAR(100),
        reference_id INT,
        from_location VARCHAR(255),
        to_location VARCHAR(255),
        notes TEXT,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
        INDEX idx_item_id (item_id),
        INDEX idx_type (type),
        INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS purchase_orders (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        supplier_id INT NOT NULL,
        order_number VARCHAR(100) UNIQUE,
        order_date DATE NOT NULL,
        expected_delivery DATE,
        status ENUM('draft', 'sent', 'received', 'partial', 'canceled') DEFAULT 'draft',
        subtotal DECIMAL(15, 2),
        tax DECIMAL(15, 2),
        total_amount DECIMAL(15, 2),
        payment_status ENUM('pending', 'paid', 'partial') DEFAULT 'pending',
        notes TEXT,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_order_number (order_number),
        INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS purchase_order_items (
        id INT PRIMARY KEY AUTO_INCREMENT,
        purchase_order_id INT NOT NULL,
        item_id INT,
        item_name VARCHAR(255) NOT NULL,
        quantity DECIMAL(10, 2) NOT NULL,
        unit VARCHAR(50),
        unit_price DECIMAL(10, 2),
        line_total DECIMAL(15, 2),
        quantity_received DECIMAL(10, 2) DEFAULT 0,
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
        FOREIGN KEY (item_id) REFERENCES inventory_items(id),
        INDEX idx_purchase_order_id (purchase_order_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",

    "CREATE TABLE IF NOT EXISTS supplier_payments (
        id INT PRIMARY KEY AUTO_INCREMENT,
        organization_id INT NOT NULL,
        supplier_id INT NOT NULL,
        purchase_order_id INT,
        amount DECIMAL(15, 2) NOT NULL,
        payment_date DATE NOT NULL,
        payment_method VARCHAR(100),
        reference VARCHAR(255),
        notes TEXT,
        created_by INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
        INDEX idx_organization_id (organization_id),
        INDEX idx_supplier_id (supplier_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
];
